import { Footer } from '@/components/footer/Footer';
import { Navbar } from '@/components/nav/Navbar';
import type { Metadata } from 'next';
import { bodyFont, headingFont, subheadingFont } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'PrepPotato',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${headingFont.variable} ${subheadingFont.variable} ${bodyFont.variable}`}
    >
      <body className="font-bodyFont">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
